### ISSUE TITLE
snoop prevents breakpoints working in vscode

### ISSUE THREAD

**Issue by abulka** [alexmojaki/snoop#10]
Using any snoop decorators prevents breakpoints from working in Visual Studio Code. The vscode debugger outputs this warning:

```
PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
```

This also happens with pysnooper.

A workaround is to `snoop.install(enabled=False)` which allows the vscode debugger breakpoints to work. Thankfully this centralised one line 'install' call disables all the snoop decorators globally - with pysnooper I had to hunt down all my decorators and actually comment them out!

**Comment by alexmojaki** [comment]
Virtually all debuggers (snoop, PySnooper, pdb, PyCharm, vscode, ...) as well as some other tools (e.g. coverage) use `sys.settrace()`, and unfortunately there's no API to make them work at the same time. I could try patching `sys.settrace()`, but it'd be really complicated, and someone else (e.g. vscode) might also patch it in an incompatible way. Unfortunately I don't think this will ever be solved.
