### ISSUE TITLE
Use pprintpp if insalled

### ISSUE THREAD

**Issue by sirex** [alexmojaki/snoop#13]
It would be nice if [pprintpp](https://pypi.org/project/pprintpp/) would be used for pretty printing values if installed instead of build-in [pprint](https://docs.python.org/3/library/pprint.html). Or at least pretty printing function should be configurable.

pprintpp gives more readable output.

**Comment by alexmojaki** [comment]
This seems like a pretty good idea.

Before making changes on my side though, can you try using it with the following code:

```python
import pprint
import pprintpp
pprint.pformat = pprintpp.pformat
```

That should make `pp` use `pprintpp`.

**Comment by sirex** [comment]
Well, that works, but does not look like a clean solution.

**Comment by alexmojaki** [comment]
@sirex see #33
