### ISSUE TITLE
Output buffering is altered

### ISSUE THREAD

**Issue by nicois** [alexmojaki/snoop#19]
When using the snoop decorator in docker compose, all my output appears to be buffered, meaning there are significant delays in when the log output is shown. 

It is not only the snoop output which is affected, but also normal logging statements. It affects buffering in the entire python application, not just the decorated functions.

If the package is installed, but nothing is decorated, there is no adverse effect.

**Comment by alexmojaki** [comment]
I can't see why this would be the case. Are you sure it's not just that the program is running more slowly?

**Comment by nicois** [comment]
I ran docker compose with pytest twice. Once with snoop, once with pysnooper. Nothing else was changed

As you can see, pysnooper shows up in the logs. Snoop does not show any output at all. Here docker compose exited pytest before snoop's buffer was flushed.

In other situations, where I decorate a more frequently called function, I do eventually see output, but significantly after the function was run. 

[pysnooper.txt](https://github.com/alexmojaki/snoop/files/4082119/pysnooper.txt)
[snoop.txt](https://github.com/alexmojaki/snoop/files/4082120/snoop.txt)

**Comment by alexmojaki** [comment]
Try flushing after each write:

```python
import sys
import snoop

def write(s):
    sys.stderr.write(s)
    sys.stderr.flush()

snoop.install(out=write)
```

**Comment by nicois** [comment]
yes, that seems to do the trick. Thanks.

**Comment by alexmojaki** [comment]
Great, thanks for the bug report!

Fixed in https://github.com/alexmojaki/snoop/commit/4da60ec3c8c4d63451ca4c0d8e0f748d6155bf3a
