### ISSUE TITLE
Can't color in pycharm run window

### ISSUE THREAD

**Issue by 625781186** [alexmojaki/snoop#20]
![image](https://user-images.githubusercontent.com/30521429/78355673-aafc3180-75e0-11ea-947f-210c7efe65a0.png)

### Env :
OS : win10
snoop : v0.2.4
pycharm : 2019.1

![image](https://user-images.githubusercontent.com/30521429/78355756-d41cc200-75e0-11ea-8ec0-713b9c80dbe9.png)

already

![image](https://user-images.githubusercontent.com/30521429/78355829-fdd5e900-75e0-11ea-8c12-8790a23cbdf7.png)

**Comment by alexmojaki** [comment]
I use PyCharm all the time, I've never seen it show escape codes (e.g. `?[39m`) in the Run output, whether or not that option is ticked in the run configuration. This looks like an issue in your PyCharm, not really related to snoop. Try looking at https://youtrack.jetbrains.com/issue/CPP-6949 and similar issues.

**Comment by 625781186** [comment]
> I use PyCharm all the time, I've never seen it show escape codes (e.g. `?[39m`) in the Run output, whether or not that option is ticked in the run configuration. This looks like an issue in your PyCharm, not really related to snoop. Try looking at https://youtrack.jetbrains.com/issue/CPP-6949 and similar issues.

Another friend of mine is in the same situation.
Can you provide your operating system and pycharm version ?

**Comment by alexmojaki** [comment]
> PyCharm 2019.3.4 (Professional Edition)
> Build #PY-193.6911.25, built on March 18, 2020
> 
> Runtime version: 11.0.6+8-b520.43 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Linux 5.3.0-40-generic
> GC: ParNew, ConcurrentMarkSweep
> Memory: 4029M
> Cores: 8
> Registry: debugger.watches.in.variables=false
> Non-Bundled Plugins: BashSupport, SvgViewer 2, com.andrey4623.rainbowcsv, com.github.alexmojaki.birdseye.pycharm, net.ashald.envfile, net.seesharpsoft.intellij.plugins.csv, org.intellij.plugins.hcl, org.plugin.dot.id, org.toml.lang, ru.adelf.idea.dotenv

It also works on Mac. The issue I linked suggests this might be a Windows problem.
