### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by chao-lai** [alexmojaki/snoop#25]
created a virtual environment. 

/Users/soft_orca/.leetcode/venv/bin/python3.8 -m pip install snoop

import snoop at top of file

run code -> get error.
ImportError: No module named snoop

**Comment by alexmojaki** [comment]
Is your virtual environment active?

What's the output of these commands?

```
/Users/soft_orca/.leetcode/venv/bin/python3.8 -m pip freeze
/Users/soft_orca/.leetcode/venv/bin/python3.8 -c 'import snoop'
```

**Comment by chao-lai** [comment]
## freeze output:

astroid==2.4.2
asttokens==2.0.4
cheap-repr==0.4.2
executing==0.5.2
isort==5.5.1
lazy-object-proxy==1.4.3
mccabe==0.6.1
Pygments==2.6.1
pylint==2.6.0
six==1.15.0
snoop==0.2.5
toml==0.10.1
wrapt==1.12.1

## import snoop output: 
nothing

**Comment by alexmojaki** [comment]
So it's installed and finds the module fine. How did you run your script? Did you `source venv/bin/activate`?

**Comment by chao-lai** [comment]
yea I did. this is how:

![image](https://user-images.githubusercontent.com/45082271/92628376-b55edd80-f29a-11ea-8f10-22ce51683b09.png)

**Comment by alexmojaki** [comment]
Running a command in the terminal may not affect the rest of the IDE. You need to make sure that when you click the Run button it uses the correct interpreter. Try running a script `import sys; print(sys.executable)` in your IDE. Anyway this is an IDE usage problem and I can't help you further.
