### ISSUE TITLE
crash or line content mismatch 

### ISSUE THREAD

**Issue by valq7711** [alexmojaki/snoop#27]
can't get it working with output to file.
It writes mismatched content for line number or crashes altogether (trying to output non existing lines)

![image](https://user-images.githubusercontent.com/11394363/99309506-9cf6da80-286a-11eb-9da0-566bdde52646.png)

**Comment by alexmojaki** [comment]
Please provide a minimal example script to reproduce with. It doesn't seem like this is related to where the output goes.

**Comment by valq7711** [comment]
I think it is somehow related to imports with parens:
```python 
from . some  import (
)
```
or using other decorators:
```python 

@mydecorator
@snoop
def foo():
    ...
```

**Comment by alexmojaki** [comment]
This code runs fine:

```python
from functools import (
    lru_cache,
    wraps
)

import snoop

@lru_cache()
@snoop
@wraps(wraps)
def foo():
    from math import (
        sin
    )
    print(1)

foo()
```

Please provide a minimal example script to reproduce with.

**Comment by valq7711** [comment]
Does your example work with output to file  `snoop.install(out= ...)`?

**Comment by alexmojaki** [comment]
Yes

**Comment by valq7711** [comment]
sorry, can't reproduce  - it works with pure python, but doesnt work in py4web app (in web server context). py4web uses machinery import - may be related to that.

**Comment by valq7711** [comment]
it writes right line number in lines like:
```Call to fun in File "some.py", line 24 ```
but mismatched content in other lines like: 
```01:51:21.72 24 | ...```

**Comment by valq7711** [comment]
sort of caught:
there is  raw ascii-art with 7 lines height in py4web.core,
removing the art solves the problem

**Comment by valq7711** [comment]
Now I have another issue: 
Py4web can reload applications using machinery, but during this process, it only reloads the application code and does not reload modules that were imported by the application. 
The issue is that after application code changing  and  reloading, snoop works, but outputs the old code.

**Comment by alexmojaki** [comment]
It sounds like the second problem might be the cause of the problem, i.e. there is only one problem. Can you reproduce any problems within a single fresh run with no reloading, i.e. starting the process from scratch?

Dynamic clever reloaders are a problem. Being able to cache source code is important for performance, and I don't know any good general way to detect that the cache is invalid. Here is a basic solution:

```python
import snoop

def reloadable_snoop(func):
    snoop.formatting.Source.for_filename(
        func.__code__.co_filename,
        func.__globals__,
        use_cache=False,
    )
    return snoop(func)

# Use it like normal @snoop
@reloadable_snoop
def foo():
    return 3

foo()
```

This is too aggressive for me to commit, it reloads the cache every time the decorator is called, which is bad if the decorator is used on a locally defined function. But it's a start for you to try out.

**Comment by valq7711** [comment]
OK, thank you, I will try it.
Also I will try to modify the reloader so that it will reload snoop when reloading any application.

**Comment by valq7711** [comment]
Your patch works fine! Thank you for your work.
Just reloading snoop.* doesnt help, due to ( as I understand) cache is held by third-party package that use another package ...

To detect that cache is invalid quite enough check mtime, no?
Also, assuming that snoop.install is invoked once per application load/reload, the following logic may be used:
1. generate and store  uuid for each install-call (`current_uuid`)
2. for each cached file-source save that uuid and file-mtime
3.
 ```python
if file_cache_uuid != current_uuid:
    mtime = os.stat(file.py).st_mtime
    if file_cache_mtime != mtime:
        cache_is_invalid = True
    file_cache_uuid, file_cache_mtime =  current_uuid, mtime
    if cache_is_invalid:
        ... # update cache
``` 
 after cache update, update file_cache_uuid and file_cache_mtime

**Comment by alexmojaki** [comment]
> Just reloading snoop.* doesnt help, due to ( as I understand) cache is held by third-party package that uses another package ...

It should work, but I guess it depends on how reloading works. Maybe you requested a reload from py4web and it didn't do it because it didn't see any changes? `importlib.reload` seems to work:

```python
from importlib import reload
import snoop.formatting

def show_cache():
    print(snoop.formatting.Source._class_local("__source_cache", {}))

@snoop
def foo():
    pass


show_cache()  # empty
foo()
show_cache()  # not empty
reload(snoop.formatting)
show_cache()  # empty again
```

**Comment by alexmojaki** [comment]
Ah, looking into it deeper, I see how it's not quite enough. Try this:

```python
from importlib import reload

reload(snoop.formatting)
reload(snoop.tracer)
```

in that exact order.

**Comment by valq7711** [comment]
This is simplified  py4web reloader code (removed try/except/logging):
```python
...
module_name = "apps.%s" % app_name 
def clear_modules():
    # all files/submodules
    names = [
        name
        for name in sys.modules
        if (name + ".").startswith(module_name + ".") \
           or name == 'snoop' or name.startswith("snoop.")  # I added only this line
    ]
    for name in names:
        del sys.modules[name]
clear_modules()
module = importlib.machinery.SourceFileLoader(
                    module_name, init
                ).load_module()
```

**Comment by valq7711** [comment]
also I tried with addition:
```python
or name == 'executing' or name.startswith( 'executing.')
```

**Comment by valq7711** [comment]
> Ah, looking into it deeper, I see how it's not quite enough. Try this:
> 
> ```python
> from importlib import reload
> 
> reload(snoop.formatting)
> reload(snoop.tracer)
> ```
> 
> in that exact order.

OK, thanks, will try asap

**Comment by alexmojaki** [comment]
The more I think about it the more I realise what a tangled mess reloading is. Let's stop looking at that. I won't be surprised if my new suggestion doesn't work.

**Comment by valq7711** [comment]
> The more I think about it the more I realise what a tangled mess reloading is. Let's stop looking at that. I won't be surprised if my new suggestion doesn't work.

yeah, still doesn't work.

**Comment by alexmojaki** [comment]
`executing` now clears caches in all Source subclasses after an `importlib.reload(module)`. Hopefully that helps with this case too.
