### ISSUE TITLE
How to: expand to see complete parameter

### ISSUE THREAD

**Issue by helphelpplease** [alexmojaki/snoop#47]
Hi, thankyou for snoop and depth setting. Super helpful.is there a setting that allows me to see entire parameter/ variable ?

For example : DeviceId='9...
deviceid is 128 characters and I would like to see it all.

Thankyou
Python 3.9, Mac 10.13.6

**Comment by alexmojaki** [comment]
Duplicate of https://github.com/alexmojaki/snoop/issues/26
