### ISSUE TITLE
upload wheel to pypi

### ISSUE THREAD

**Issue by matan-h** [alexmojaki/snoop#48]
it will be good if the snoop whl  will be in pypi (useful for some projects, like `pyodide` that fetch pypi)

**Comment by alexmojaki** [comment]
Ah, so does https://github.com/alexmojaki/futurecoder/issues/214 come from you? Are you creating your own project with pyodide?

**Comment by matan-h** [comment]
yes, I try to create simple web code editor with ddebug, that require snoop.

**Comment by alexmojaki** [comment]
Done!
