### ISSUE TITLE
Tests hang on Python 3.9+ due to thread ident being clobbered

### ISSUE THREAD

**Issue by gpshead** [alexmojaki/snoop#52]
This line https://github.com/alexmojaki/snoop/blob/v0.4.1/tests/test_snoop.py#L26 isn't safe to do to Python.

`tox -e py39` hangs when it should be exiting pytest as a result.

Any of the tests/sample_results/ files containing a thread id need to be pre-processed to insert the actual live thread id from the test instead if you want to do == comparisons on them

**Comment by alexmojaki** [comment]
Thank you, I didn't even realise I had a failing build badge! Fixed in https://github.com/alexmojaki/snoop/commit/16f32ce5ff6693d5153b465ed12ae994f44bdc00
