### ISSUE TITLE
Enable snoop during a recursive trace

### ISSUE THREAD

**Issue by skeledrew** [alexmojaki/snoop#53]
Hi,

I'm working on a debugging toolbox which includes snoop (as well as Birdseye). One of the features is to automatically wrap a function that raises while tracing and, since there's no way to move execution back to the point before the function was run (without maybe some arcade bytecode hacking), eval the wrapped function again during the handling of the exception. One of the things that wrapper does is wrap the function with `spy` before running it again. I find that Birdseye works fine, however snoop provides no feedback. Is this the intended behavior? How can I work around it?

**Comment by alexmojaki** [comment]
Running the function from the beginning again sounds very likely to cause more confusion and frustration while debugging. Any extra side effects that happen during the rerun can mislead the user. 

Assuming you really want to do this (which so far I'm against) can you clarify further what you're doing? It's hard to know how you're using snoop and why it might not be working.

**Comment by skeledrew** [comment]
So the issue is I find it tedious to be always adding and removing decorators during development, so I want to automate that process. As such I've created a manager that is always tracing during development, and handles unanticipated exceptions by getting the arguments, wrapping with spy, and evaling again with those arguments. I'll also likely be adding hot reloading. Does that help? I'm aware that global changes and mutable arguments for example can lead to state corruption, and will be putting in a warning for when it seems that's likely.

**Comment by alexmojaki** [comment]
Can you share some minimal code?

**Comment by skeledrew** [comment]
Sharing the [entire WiP](https://gist.github.com/skeledrew/9509cfce9f9be193316dd819a18629c7) as it's a bit complex to extract a working relevant bit. Primary areas of interest are lines 112 and 226. I hope that's OK.

**Comment by alexmojaki** [comment]
OK, I think I get it now. The problem is that Python itself doesn't allow recursive sys.settrace, i.e. you can't trace the code that's running during the current trace function. Here's some discussions from when PySnooper ran into this:

https://mail.python.org/archives/list/python-ideas@python.org/thread/XUUZIP2TOB7EMTWBQJ667HJ6HFVEDVK7/#XUUZIP2TOB7EMTWBQJ667HJ6HFVEDVK7

https://github.com/cool-RR/PySnooper/issues/46#issuecomment-486571438

**Comment by skeledrew** [comment]
Oh, I see. Thanks for those references. There still remains the question re Birdseye though: why does it still work at that level? How does its mechanism differ from snoop's?

I guess perhaps what I'll end up doing is modifying the modules at import time so everything is wrapped by default. That however means I'll have to find a sane way to ignore all expected exceptions...

**Comment by skeledrew** [comment]
Ah, I've found the Birdseye "How it works". Thanks again!
