### ISSUE TITLE
Unreadable color on light background

### ISSUE THREAD

**Issue by zasdfgbnm** [alexmojaki/snoop#6]
![image](https://user-images.githubusercontent.com/1032377/60935487-0e4a7480-a298-11e9-9971-0b1530e9b1c8.png)
Changing the profile solves the problem
![image](https://user-images.githubusercontent.com/1032377/60935545-33d77e00-a298-11e9-88c7-a43953e6034e.png)
but we might want it to work on any profile

**Comment by alexmojaki** [comment]
Thanks for the feedback! This is my first issue! Fixed in https://github.com/alexmojaki/snoop/commit/e603b5fff68e7d9c08cebfd551e6d67fdf6ef20d

There is documentation in the README about how to choose a custom color scheme. Did you see it? In any case, clearly that's not enough.

**Comment by zasdfgbnm** [comment]
@alexmojaki Thanks for the quick fix! To be honest, I didn't read the README much. I usually rely on the software to provide me a good default option to use. But I just found that part, I think it is clear.
