### ISSUE TITLE
Add logger support

### ISSUE THREAD

**Issue by evan0greenup** [alexmojaki/snoop#65]
Currently, snoop will dump all debug info into stdout, However, if there is program normal output via stdout. It would be too messy. 

How about add option `logger` in the `snoop()` to dump all the debug information into the given logger.

**Comment by evan0greenup** [comment]
@alexmojaki  , is it difficult?

**Comment by alexmojaki** [comment]
See https://github.com/alexmojaki/snoop#output-configuration

The default is stderr, not stdout.

You can use logging with e.g. `snoop.install(out=logger.info)`
