### ISSUE TITLE
A question before using: can this work with pdb step by step debugging

### ISSUE THREAD

**Issue by tumble-weed** [alexmojaki/snoop#66]
Hello,
from the descriptions, this project looks great. I have a particular use case i wanted to know snoop can work for.
I have to do step by step debugging with pdb for data scientific applications, and it'd be great if snoop can print out its details every time i do 's', 'c' or 'n'. is this part of the functionality?
thanks

**Comment by alexmojaki** [comment]
No, you can't use snoop and pdb at the same time.
