### ISSUE TITLE
multiple snoop configs display weirdly

### ISSUE THREAD

**Issue by abulka** [alexmojaki/snoop#9]
Defining multiple snoops cause the console output stderr to dispaly two extra snoop outputs which are  "Call to Tracer.__call__." and  Return value from Tracer.__call__. which also contain extra long ".............." lines 

```
snoop.install()
config = snoop.Config()

@snoop
@config.snoop
def get_repo_tree(user, repo, branch, logged_in_user=None):
  blah
```

I would expect two normal snoop outputs, instead I get one normal output wrapped in these tracer calls:

```
09:44:51.06 >>> Call to Tracer.__call__.<locals>.simple_wrapper in File "/Users/andy/.local/share/virtualenvs/gituml-Iv6Hkut1/lib/python3.6/site-packages/snoop/tracer.py", line 167
09:44:51.06 .............. args = ('matplotlib', 'matplotlib', '99d8900eacaad01b1ff6e5d482e4e17683dd36be')
09:44:51.06 .............. len(args) = 3
09:44:51.06 .............. kwargs = {'logged_in_user': <SimpleLazyObject: <User: andy22>>}
09:44:51.06 .............. len(kwargs) = 1
09:44:51.06 .............. function = <function get_repo_tree at 0x10d71b730>
09:44:51.06 .............. self = <snoop.configuration.Config.__init__.<locals>.ConfiguredTracer object at 0x10d6d8198>
09:44:51.06  167 |         def simple_wrapper(*args, **kwargs):
09:44:51.07  168 |             with self:
09:44:51.07  169 |                 return function(*args, **kwargs)

09:44:51.07 >>> Call to get_repo_tree in File "/Users/Andy/Devel/gituml/lib/repo/repo_tree.py", line 58
09:44:51.07 ...... user = 'matplotlib'
09:44:51.07 ...... repo = 'matplotlib'
09:44:51.07 ...... branch = '99d8900eacaad01b1ff6e5d482e4e17683dd36be'
09:44:51.07 ...... logged_in_user = <SimpleLazyObject: <User: andy22>>
09:44:51.07   58 | def get_repo_tree(user, repo, branch, logged_in_user=None):
09:44:51.07   73 |     if is_sha(branch):
09:44:51.07   74 |         return get_repo_tree_sha(user, repo, branch)
https://api.github.com/repos/matplotlib/matplotlib/git/trees/99d8900eacaad01b1ff6e5d482e4e17683dd36be?recursive=true
09:44:51.09 <<< Return value from get_repo_tree: ('{"sha":"99d8900eacaad01b1ff6e5d482e4e17683dd36be...1befdb06113c867356e4bea861e"}],"truncated":false}', '99d8900eacaad01b1ff6e5d482e4e17683dd36be')

09:44:51.10 <<< Return value from Tracer.__call__.<locals>.simple_wrapper: ('{"sha":"99d8900eacaad01b1ff6e5d482e4e17683dd36be...1befdb06113c867356e4bea861e"}],"truncated":false}', '99d8900eacaad01b1ff6e5d482e4e17683dd36be')
09:44:51.10  169 |                 return function(*args, **kwargs)
09:44:51.10 ...................... args = ('matplotlib', 'matplotlib', '99d8900eacaad01b1ff6e5d482e4e17683dd36be')
09:44:51.10 ...................... len(args) = 3
09:44:51.10 ...................... kwargs = {'logged_in_user': <SimpleLazyObject: <User: andy22>>}
09:44:51.10 ...................... len(kwargs) = 1
09:44:51.10 ...................... function = <function get_repo_tree at 0x10d71b7b8>
09:44:51.10 ...................... self = <snoop.configuration.Config.__init__.<locals>.ConfiguredTracer object at 0x10d5bd358>
09:44:51.10 <<< Exit with block in Tracer.__call__.<locals>.simple_wrapper
```

When the second snoop config is configured to go soley to a file, 

```
snoop.install()
config = snoop.Config(out="junk.txt")
```

the nice normal snoop output fails to appear in stderr at all, and the two unwanted "tracer call outputs" appear in stderr instead. Output does thankfully appear in the output file.

I'm assuming I am using snoop correctly, by adding the two decorators one after the other, before the target def.  If I don't add the second snoop decorator then it doesn't take effect, so it seems that must be the way to do it.

**Comment by alexmojaki** [comment]
This is not related to multiple configs, just to decorating twice. This will show similar behaviour:

```python
import snoop

@snoop
@snoop
def foo():
    x = 2

foo()
```

The `@snoop` decorator returns a function `simple_wrapper` which is what the second `@snoop` decorator receives as an argument. The same kind of thing happens in the second README example with `cache`.

What's your use case here? Are you trying to write to both stderr and a file? In that case I'd recommend passing a function to `out` which does those two things.

**Comment by abulka** [comment]
Ah, I see. 
So the multiple snoop config idea is really meant to have some functions’ output going to stderr and other different functions going to file (or whatever). Not to combine the two decorators. 

Yes my use case is to get the nice stderr coloured output and also a record of that output to file. I’m ok with writing a function to do both, but it sounds like I’ll lose my lovely stderr colours, and will have to implement my own file name path parameter handling? Hmm, actually might just stick with the out of the box coloured stderr experience. Thanks.

**Comment by alexmojaki** [comment]
> So the multiple snoop config idea is really meant to have some functions’ output going to stderr and other different functions going to file (or whatever). Not to combine the two decorators.

That's right.

> Yes my use case is to get the nice stderr coloured output and also a record of that output to file.

You could write to a file and set `color=True`. Then the file will contain colour and you can use `tail -f` to see it.

**Comment by alexmojaki** [comment]
Seems this issue has been resolved. Let me know if you're still not happy.
